export const NAUTILUS = {};

/**
 * The set of Ability Scores used within the sytem.
 * @type {Object}
 */
NAUTILUS.items = {
  "distance":"ITEM.TypeDistance",
  "melee":"ITEM.TypeMelee",
};

NAUTILUS.pression = {
  "0":"NAUTILUS.PRESSION.Facile",
  "5":"NAUTILUS.PRESSION.Nulle",
  "6":"NAUTILUS.PRESSION.Legere",
  "7":"NAUTILUS.PRESSION.Importante",
  "8":"NAUTILUS.PRESSION.Critique",
  "11":"NAUTILUS.PRESSION.Abyssale",
};

NAUTILUS.aptitudes = {
  'agir':'NAUTILUS.PERSONNAGE.APTITUDES.Agir',
  'connaitre':'NAUTILUS.PERSONNAGE.APTITUDES.Connaitre',
  'endurer':'NAUTILUS.PERSONNAGE.APTITUDES.Endurer',
  'forcer':'NAUTILUS.PERSONNAGE.APTITUDES.Forcer',
  'percevoir':'NAUTILUS.PERSONNAGE.APTITUDES.Percevoir',
  'simposer':'NAUTILUS.PERSONNAGE.APTITUDES.SImposer',
  'savoirfaire':'NAUTILUS.PERSONNAGE.APTITUDES.SavoirFaire',
  'sebattre':'NAUTILUS.PERSONNAGE.APTITUDES.SeBattre',
  'secontroler':'NAUTILUS.PERSONNAGE.APTITUDES.SeControler',
  'viser':'NAUTILUS.PERSONNAGE.APTITUDES.Viser',
  'manoeuvre':'NAUTILUS.VAISSEAUX.APTITUDES.Manoeuvre',
  'maniabilite':'NAUTILUS.VAISSEAUX.APTITUDES.Maniabilite',
  'plonger':'NAUTILUS.VAISSEAUX.APTITUDES.Plonger',
  'endurance':'NAUTILUS.VAISSEAUX.APTITUDES.Endurance',
  'chasse':'NAUTILUS.VAISSEAUX.APTITUDES.Chasse',
  'coque':'NAUTILUS.VAISSEAUX.APTITUDES.Coque',
  'puissance':'NAUTILUS.VAISSEAUX.APTITUDES.Puissance',
  'eperonnage':'NAUTILUS.VAISSEAUX.APTITUDES.Eperonnage',
  'detection':'NAUTILUS.VAISSEAUX.APTITUDES.Detection',
  'fanal':'NAUTILUS.VAISSEAUX.APTITUDES.Fanal'
};

NAUTILUS.consequence = {
  's0':'NAUTILUS.PERSONNAGE.SANTE.CONSEQUENCES.Terrasse',
  's1':'NAUTILUS.PERSONNAGE.SANTE.CONSEQUENCES.EtatCritique',
  's2':'NAUTILUS.PERSONNAGE.SANTE.CONSEQUENCES.BlesseGravement',
  's3':'NAUTILUS.PERSONNAGE.SANTE.CONSEQUENCES.Blesse',
  's4':'NAUTILUS.PERSONNAGE.SANTE.CONSEQUENCES.Epuise',
  's5':'NAUTILUS.PERSONNAGE.SANTE.CONSEQUENCES.Fatigue',
  's6':'NAUTILUS.PERSONNAGE.SANTE.CONSEQUENCES.PleineForme',
};

NAUTILUS.recup = {
  's0':'NAUTILUS.PERSONNAGE.SANTE.RECUPERATION.Special',
  's1':'NAUTILUS.PERSONNAGE.SANTE.RECUPERATION.Special',
  's2':'NAUTILUS.PERSONNAGE.SANTE.RECUPERATION.48H',
  's3':'NAUTILUS.PERSONNAGE.SANTE.RECUPERATION.24H',
  's4':'NAUTILUS.PERSONNAGE.SANTE.RECUPERATION.12H',
  's5':'NAUTILUS.PERSONNAGE.SANTE.RECUPERATION.6H',
  's6':'-',
};

NAUTILUS.vm = {
  'liberte':"NAUTILUS.PERSONNAGE.VALEURSMORALES.Liberte",
  'verite':"NAUTILUS.PERSONNAGE.VALEURSMORALES.Verite",
  'justice':"NAUTILUS.PERSONNAGE.VALEURSMORALES.Justice",
  'pacifisme':"NAUTILUS.PERSONNAGE.VALEURSMORALES.Pacifisme",
  'progres':"NAUTILUS.PERSONNAGE.VALEURSMORALES.Progres",
};